#name: Generate Changelog
#
#on:
#  push:
#    tags:
#      - '*'
#
#jobs:
#  generate_changelog:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Generate changelog
#        run: |
#          npm install -g conventional-changelog-cli
#          conventional-changelog -p angular -i CHANGELOG.md -s
