name: Generate Changelog

on:
  push:
    tags:
      - '*'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate changelog
        uses: actions/changelog-maker-action@v2
        with:
          tag_from: ${{ github.ref }}
          tag_to: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          output_file: CHANGELOG.md
          title: Changelog
