name: Release

on:
  create:
    types: [tag]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run the Gradle test task
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
      - name: Generate changelog
        uses: actions/changelog-maker-action@v2
        with:
          tag_from: ${{ github.ref }}
          tag_to: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          output_file: CHANGELOG.md
          title: Changelog
      - name: Create release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload artifacts
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:
            - build/libs/faircorp-0.0.1-SNAPSHOT.jar
          asset_name:
            - faircorp-0.0.1-SNAPSHOT.jar
          asset_content_type: application/java-archive

      - name: Upload documentation
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: README.md
          asset_name: documentation.zip
          asset_content_type: application/zip
