- name: Create release
  if: success()
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: ${{ github.ref }}
    release_name: Release ${{ github.ref }}
    body: ${{ steps.generate_changelog.outputs.data }}
- name: Upload artifacts
  if: success()
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: build/libs/*.jar
    asset_name: faircorp-${{ github.ref }}.jar
    asset_content_type: application/java-archive
- name: Upload documentation
  if: success()
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: documentation/*
    asset_name: documentation.zip
    asset_content_type: application/zip
